"""initial saas schema

Revision ID: 176e813d48e3
Revises: 
Create Date: 2026-04-09 14:33:50.678373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176e813d48e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('plan_started_at', sa.DateTime(), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('etablissements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('secteur', sa.String(), nullable=True),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('site_web', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('siege_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['siege_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siret')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('probite_scores',
    sa.Column('etablissement_id', sa.String(), nullable=False),
    sa.Column('score_global', sa.Float(), nullable=True),
    sa.Column('taux_reponse', sa.Float(), nullable=True),
    sa.Column('delai_moyen_reponse', sa.Float(), nullable=True),
    sa.Column('ghosting_rate', sa.Float(), nullable=True),
    sa.Column('nb_candidatures', sa.Integer(), nullable=True),
    sa.Column('nb_users_uniques', sa.Integer(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('etablissement_id')
    )
    op.create_table('succursales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('etablissement_id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('etablissement_id', sa.String(), nullable=False),
    sa.Column('client_final_id', sa.String(), nullable=True),
    sa.Column('succursale_id', sa.String(), nullable=True),
    sa.Column('poste', sa.String(), nullable=False),
    sa.Column('url_offre', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('date_candidature', sa.DateTime(), nullable=True),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.Column('salaire_vise', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_final_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['succursale_id'], ['succursales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('etablissement_id', sa.String(), nullable=True),
    sa.Column('succursale_id', sa.String(), nullable=True),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('poste', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('email_pro', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('etablissement_id IS NOT NULL OR succursale_id IS NOT NULL', name='contact_rattache'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], ),
    sa.ForeignKeyConstraint(['succursale_id'], ['succursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidature_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidature_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ancien_statut', sa.String(), nullable=True),
    sa.Column('nouveau_statut', sa.String(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_interactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('appreciation', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('email_perso', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('derniere_interaction', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'user_id', name='uq_interaction_contact_user')
    )
    op.create_table('relances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidature_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('date_prevue', sa.DateTime(), nullable=False),
    sa.Column('date_effectuee', sa.DateTime(), nullable=True),
    sa.Column('canal', sa.String(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relances')
    op.drop_table('contact_interactions')
    op.drop_table('candidature_events')
    op.drop_table('contacts')
    op.drop_table('candidatures')
    op.drop_table('succursales')
    op.drop_table('probite_scores')
    op.drop_table('password_reset_tokens')
    op.drop_table('etablissements')
    op.drop_table('users')
    # ### end Alembic commands ###
