"""replace user with profile for supabase auth

Revision ID: 8a65c6570d66
Revises: 176e813d48e3
Create Date: 2026-04-09 18:33:47.716247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a65c6570d66'
down_revision: Union[str, Sequence[str], None] = '176e813d48e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('password_reset_tokens')
    op.drop_table('users')
    op.drop_table('application_contacts')
    op.drop_table('organizations')
    op.drop_table('events')
    op.drop_constraint(None, 'candidature_events', type_='foreignkey')
    op.create_foreign_key(None, 'candidature_events', 'profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'candidatures', type_='foreignkey')
    op.create_foreign_key(None, 'candidatures', 'profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'contact_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'contact_interactions', 'profiles', ['user_id'], ['id'])
    op.add_column('contacts', sa.Column('etablissement_id', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('succursale_id', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('prenom', sa.String(), nullable=False))
    op.add_column('contacts', sa.Column('nom', sa.String(), nullable=False))
    op.add_column('contacts', sa.Column('poste', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('email_pro', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('created_by', sa.String(), nullable=True))
    op.alter_column('contacts', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('contacts', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('contacts', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'profiles', ['created_by'], ['id'])
    op.create_foreign_key(None, 'contacts', 'etablissements', ['etablissement_id'], ['id'])
    op.create_foreign_key(None, 'contacts', 'succursales', ['succursale_id'], ['id'])
    op.drop_column('contacts', 'role')
    op.drop_column('contacts', 'notes')
    op.drop_column('contacts', 'last_name')
    op.drop_column('contacts', 'first_name')
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'organization_id')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'is_recruiter')
    op.drop_constraint(None, 'etablissements', type_='foreignkey')
    op.create_foreign_key(None, 'etablissements', 'profiles', ['created_by'], ['id'])
    op.drop_constraint(None, 'relances', type_='foreignkey')
    op.create_foreign_key(None, 'relances', 'profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'succursales', type_='foreignkey')
    op.create_foreign_key(None, 'succursales', 'profiles', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'succursales', type_='foreignkey')
    op.create_foreign_key(None, 'succursales', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'relances', type_='foreignkey')
    op.create_foreign_key(None, 'relances', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'etablissements', type_='foreignkey')
    op.create_foreign_key(None, 'etablissements', 'users', ['created_by'], ['id'])
    op.add_column('contacts', sa.Column('is_recruiter', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    op.add_column('contacts', sa.Column('email', sa.TEXT(), nullable=True))
    op.add_column('contacts', sa.Column('organization_id', sa.INTEGER(), nullable=True))
    op.add_column('contacts', sa.Column('phone', sa.TEXT(), nullable=True))
    op.add_column('contacts', sa.Column('first_name', sa.TEXT(), nullable=False))
    op.add_column('contacts', sa.Column('last_name', sa.TEXT(), nullable=False))
    op.add_column('contacts', sa.Column('notes', sa.TEXT(), nullable=True))
    op.add_column('contacts', sa.Column('role', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'organizations', ['organization_id'], ['id'])
    op.alter_column('contacts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('contacts', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('contacts', 'linkedin_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('contacts', 'created_by')
    op.drop_column('contacts', 'email_pro')
    op.drop_column('contacts', 'poste')
    op.drop_column('contacts', 'nom')
    op.drop_column('contacts', 'prenom')
    op.drop_column('contacts', 'succursale_id')
    op.drop_column('contacts', 'etablissement_id')
    op.drop_constraint(None, 'contact_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'contact_interactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'candidatures', type_='foreignkey')
    op.create_foreign_key(None, 'candidatures', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'candidature_events', type_='foreignkey')
    op.create_foreign_key(None, 'candidature_events', 'users', ['user_id'], ['id'])
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ts', sa.TEXT(), nullable=False),
    sa.Column('entity_type', sa.TEXT(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('payload_json', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'AUTRE'"), nullable=False),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('application_contacts',
    sa.Column('application_id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'contact_id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('nom', sa.VARCHAR(), nullable=True),
    sa.Column('prenom', sa.VARCHAR(), nullable=True),
    sa.Column('plan', sa.VARCHAR(), nullable=True),
    sa.Column('plan_started_at', sa.DATETIME(), nullable=True),
    sa.Column('plan_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('final_customer_organization_id', sa.INTEGER(), nullable=True),
    sa.Column('company', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('job_url', sa.TEXT(), nullable=True),
    sa.Column('applied_at', sa.TEXT(), nullable=True),
    sa.Column('next_followup_at', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['final_customer_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
