import { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom';
import { z } from 'zod';
import { supabase } from '../lib/supabase';
import { useI18n } from '../i18n';
import classes from './Auth.module.css';
import { AuthLanguageSwitcher } from '../components/atoms/AuthLanguageSwitcher';
type ForgotPasswordForm={email:string};
export function ForgotPasswordPage(){const {t}=useI18n();const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const schema=useMemo(()=>z.object({email:z.string().email(t('auth.forgot.emailInvalid'))}),[t]);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<ForgotPasswordForm>({defaultValues:{email:''}});const onSubmit=handleSubmit(async(values)=>{const parsed=schema.safeParse(values);if(!parsed.success){setError(parsed.error.issues[0]?.message??t('auth.invalidForm'));return}try{setError(null);const {error:supabaseError}=await supabase.auth.resetPasswordForEmail(parsed.data.email,{redirectTo:`${window.location.origin}/reset-password`});if(supabaseError)throw supabaseError;setMessage(t('auth.forgot.successMessage'))}catch{setError(t('auth.forgot.errorMessage'))}});return <section className={classes.shell}><AuthLanguageSwitcher /><div className={classes.card}><Link className={classes.back} to="/login">{t('auth.forgot.backLink')}</Link><span className="ot-badge" data-tone="accent">{t('auth.forgot.badge')}</span><h1>{t('auth.forgot.title')}</h1><p>{t('auth.forgot.subtitle')}</p><form className={classes.form} onSubmit={onSubmit}><label className="ot-field"><span>{t('auth.emailLabel')}</span><input className="ot-control" type="email" autoComplete="email" placeholder={t('auth.emailPlaceholder')} {...register('email')}/>{errors.email&&<small className={classes.fieldError}>{errors.email.message}</small>}</label>{message&&<div className="ot-alert" data-tone="success">{message}</div>}{error&&<div className="ot-alert" data-tone="error">{error}</div>}<button className="ot-button" data-variant="primary" type="submit" disabled={isSubmitting}>{isSubmitting?'…':t('auth.forgot.submit')}</button></form></div></section>}
