import { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, Navigate, useLocation } from 'react-router-dom';
import { z } from 'zod';
import { useAuth } from '../context/AuthContext';
import { useI18n } from '../i18n';
import { getLoginMessage, getSafeLoginDestination } from '../utils/authNavigation';
import { AuthLanguageSwitcher } from '../components/atoms/AuthLanguageSwitcher';
import classes from './Login.module.css';

type LoginFormData = { email: string; password: string };
export function LoginPage() {
  const location = useLocation(); const { signIn, isAuthenticated, isLoading } = useAuth(); const { t } = useI18n();
  const [formError, setFormError] = useState<string | null>(null); const successMessage = getLoginMessage(location);
  const loginSchema = useMemo(() => z.object({ email: z.string().email(t('auth.emailInvalid')), password: z.string().min(8, t('auth.passwordMin')) }), [t]);
  const { register, handleSubmit, setError, clearErrors, formState: { errors, isSubmitting } } = useForm<LoginFormData>({ defaultValues: { email: '', password: '' } });
  if (!isLoading && isAuthenticated) return <Navigate to={getSafeLoginDestination(location)} replace />;
  const onSubmit = handleSubmit(async (values) => { const result = loginSchema.safeParse(values); if (!result.success) { clearErrors(); result.error.issues.forEach((issue) => { const field = issue.path[0]; if (field === 'email' || field === 'password') setError(field, { type: 'manual', message: issue.message }); }); setFormError(result.error.issues[0]?.message ?? t('auth.invalidForm')); return; } try { setFormError(null); clearErrors(); await signIn(result.data.email, result.data.password); } catch { setFormError(t('auth.login.error')); } });
  return <section className={classes.shell}><AuthLanguageSwitcher /><div className={classes.frame}><aside className={classes.story}><span className={classes.eyebrow}>{t('auth.login.storyEyebrow')}</span><h1 className={classes.storyTitle}>{t('auth.login.storyTitle')}</h1><p className={classes.storyDesc}>{t('auth.login.storyDesc')}</p><div className={classes.points}>{[{ title: t('auth.login.point1Title'), desc: t('auth.login.point1Desc') }, { title: t('auth.login.point2Title'), desc: t('auth.login.point2Desc') }, { title: t('auth.login.point3Title'), desc: t('auth.login.point3Desc') }].map((point) => <div key={point.title} className={classes.point}><strong>{point.title}</strong><span>{point.desc}</span></div>)}</div></aside><div className={classes.panel}><Link className={classes.back} to="/">{t('auth.login.backLink')}</Link><h2>{t('auth.login.title')}</h2><p className={classes.subtitle}>{t('auth.login.subtitle')}</p><form className={classes.form} onSubmit={onSubmit}>{successMessage&&<div className="ot-alert" data-tone="success">{successMessage}</div>}<label className="ot-field"><span>{t('auth.emailLabel')}</span><input className="ot-control" type="email" autoComplete="email" autoCapitalize="none" autoCorrect="off" placeholder={t('auth.emailPlaceholder')} aria-invalid={Boolean(errors.email)} {...register('email')}/>{errors.email&&<small className={classes.fieldError}>{errors.email.message}</small>}</label><label className="ot-field"><span>{t('auth.passwordLabel')}</span><input className="ot-control" type="password" autoComplete="current-password" placeholder={t('auth.login.passwordPlaceholder')} aria-invalid={Boolean(errors.password)} {...register('password')}/><small className={classes.hint}>{t('auth.login.passwordHint')}</small>{errors.password&&<small className={classes.fieldError}>{errors.password.message}</small>}</label>{formError&&<div className="ot-alert" data-tone="error">{formError}</div>}<button className="ot-button" data-variant="primary" type="submit" disabled={isSubmitting}>{isSubmitting?'…':t('auth.login.submit')}</button></form><p className={classes.meta}><Link to="/forgot-password">{t('auth.login.forgotLink')}</Link>{' · '}{t('auth.login.noAccount')}{' '}<Link to="/register">{t('auth.login.registerLink')}</Link></p></div></div></section>;
}
