import { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { supabase } from '../lib/supabase';
import { useI18n } from '../i18n';
import classes from './Auth.module.css';
type ResetPasswordForm={password:string;confirmPassword:string};
export function ResetPasswordPage(){const navigate=useNavigate();const {t}=useI18n();const [error,setError]=useState<string|null>(null);const [ready,setReady]=useState(false);const schema=useMemo(()=>z.object({password:z.string().min(8,t('auth.reset.passwordMin')),confirmPassword:z.string().min(8,t('auth.reset.confirmMin'))}).refine((value)=>value.password===value.confirmPassword,{message:t('auth.reset.passwordMismatch'),path:['confirmPassword']}),[t]);const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<ResetPasswordForm>({defaultValues:{password:'',confirmPassword:''}});useEffect(()=>{const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY')setReady(true)});return()=>subscription.unsubscribe()},[]);const onSubmit=handleSubmit(async(values)=>{const parsed=schema.safeParse(values);if(!parsed.success){setError(parsed.error.issues[0]?.message??t('auth.invalidForm'));return}try{setError(null);const {error:supabaseError}=await supabase.auth.updateUser({password:parsed.data.password});if(supabaseError)throw supabaseError;navigate('/login',{replace:true,state:{message:t('auth.reset.successMessage')}})}catch(err){setError(err instanceof Error?err.message:t('auth.reset.invalidLink'))}});if(!ready)return <section className={classes.shell}><div className={classes.card}><p>{t('auth.reset.waiting')}</p><Link to="/forgot-password">{t('auth.reset.requestNew')}</Link></div></section>;return <section className={classes.shell}><div className={classes.card}><span className="ot-badge" data-tone="accent">{t('auth.reset.badge')}</span><h1>{t('auth.reset.title')}</h1><p>{t('auth.reset.subtitle')}</p><form className={classes.form} onSubmit={onSubmit}><label className="ot-field"><span>{t('auth.reset.passwordLabel')}</span><input className="ot-control" type="password" autoComplete="new-password" {...register('password')}/>{errors.password&&<small className={classes.fieldError}>{errors.password.message}</small>}</label><label className="ot-field"><span>{t('auth.reset.confirmLabel')}</span><input className="ot-control" type="password" autoComplete="new-password" {...register('confirmPassword')}/>{errors.confirmPassword&&<small className={classes.fieldError}>{errors.confirmPassword.message}</small>}</label>{error&&<div className="ot-alert" data-tone="error">{error}</div>}<button className="ot-button" data-variant="primary" type="submit" disabled={isSubmitting}>{isSubmitting?'…':t('auth.reset.submit')}</button></form><Link to="/forgot-password">{t('auth.reset.requestNew')}</Link></div></section>}
